# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ANIDESU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ANIDESU
  pod 'Alamofire'
  pod 'Cosmos', '~> 16.0'
  pod 'ESTabBarController-swift'
  pod 'Eureka'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FBSDKCoreKit', '4.38.1'
  pod 'FBSDKLoginKit', '4.38.1'
  pod 'Hero'
  pod 'IGListKit', '~> 3.0'
  pod 'IHKeyboardAvoiding'
  pod 'MBProgressHUD'
  pod 'Kingfisher'
  pod 'Player', '~> 0.12.0'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Tabman', '~> 2.1'
  pod 'UITextView+Placeholder'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['MBProgressHUD', 'Hero'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end

  target 'ANIDESUTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
