# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ANIDESU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ANIDESU
  pod 'Alamofire'
  pod 'Apollo'
  pod 'Cosmos', '~> 16.0'
  pod 'ESTabBarController-swift'
  pod 'Eureka'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Hero'
  pod 'IHKeyboardAvoiding'
  pod 'MBProgressHUD'
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Tabman', '~> 2.1'
  pod 'UITextView+Placeholder'
  pod 'WCLShineButton'
  
  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end

  target 'ANIDESUTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
